Credit Card UI changes
SimformSolutionsPvtLtd/flutter_credit_card pull request #122
Opened 2022-12-13 13:20 UTC by faiyaz-shaikh

Credit Card Example UI changes

2022-12-20 05:26 UTC, dhvanit-v-simformsolutions commented on lib/credit_card_widget.dart
> +            Align(
We can make extension for checking null and not empty. Like this 
///Extension on nullable strings
extension NullableStringExtension on String? {
  ///checks if string is null or empty.
  bool get isNullOrEmpty => this == null || (this?.isEmpty ?? false);

  ///checks if string is not null and not empty.
  bool get isNotNullAndNotEmpty => this != null && (this?.isNotEmpty ?? false);
}

2022-12-20 05:33 UTC, dhvanit-v-simformsolutions commented on lib/credit_card_widget.dart
>                padding: const EdgeInsets.only(left: 16),
Give horizontal padding here and remove padding from line number 326, I guess it will reflect same as expected.

2022-12-20 05:34 UTC, dhvanit-v-simformsolutions requested changes
Please make changes

2022-12-20 05:35 UTC, dhvanit-v-simformsolutions commented on lib/credit_card_widget.dart
>            if (widget.bankName != null && widget.bankName!.isNotEmpty)
Suggestion : We can make extension for checking null and not empty at same time . Like this,

extension NullableStringExtension on String? {

bool get isNullOrEmpty => this == null || (this?.isEmpty ?? false);

bool get isNotNullAndNotEmpty => this != null && (this?.isNotEmpty ?? false);
}

2023-01-13 13:23 UTC, DhvanitVaghani requested changes

2023-01-13 13:23 UTC, DhvanitVaghani commented on lib/credit_card_widget.dart
> +          if (widget.bankName?.isNotEmpty == true)
You can pass directly condition without comparing it. And nullable variable troubling then add default value false

2023-01-13 13:23 UTC, DhvanitVaghani commented on lib/credit_card_widget.dart
> +                  widget.bankName!,
Null check

2023-01-16 05:43 UTC, DhvanitVaghani approved these changes

2023-01-16 09:22 UTC, merged