:bug: Update readme file
SimformSolutionsPvtLtd/flutter_credit_card pull request #153
Opened 2023-10-04 06:06 UTC by manojSimfrom

2023-10-04 06:10 UTC, vatsaltanna commented on README.md
> -      themeColor: Colors.black, // Required
please add breaking change section in readme.

2023-10-05 06:09 UTC, aditya-css requested changes

2023-10-05 06:09 UTC, aditya-css commented on lib/src/models/input_configuration.dart
> +  const InputConfiguration({
Please add documentation comment stating the use of this class.

2023-10-05 06:09 UTC, aditya-css commented on README.md
> +- `themeColor`, `textColor`, and `cursorColor` have been removed from `CreditCardForm` as it can't detect the application theme. Please check out the example app to learn how to apply those using `Th
Please mention removal of input decoration fields and how to use in the newer version.

2023-10-05 06:09 UTC, aditya-css commented on README.md
> +        cvvCodeDecoration: const InputDecoration(
remove `const` from `InputDecoration` widget as it is specified at the parent constructor and thus is not needed.

2023-10-05 07:00 UTC, vatsaltanna commented on CHANGELOG.md
> +  - Updated `readme.md` to have migration guide to Version 4.0.0.
we can remove this.

2023-10-05 07:04 UTC, aditya-css approved these changes

2023-10-05 07:04 UTC, vatsaltanna approved these changes

2023-10-05 09:45 UTC, merged