The cards expired date validation control bux fixed.
SimformSolutionsPvtLtd/flutter_credit_card pull request #66
Opened 2021-10-03 16:06 UTC by ocakliemre

The expiry date on the cards should be based on the last day of that month. Since the current structure is based only on the month, it does validation not work correctly. As a bug fix, the last day of the month was found and added to the card expiry date.

2022-08-25 08:50 UTC, DhavalRKansara commented
@ocakliemre This branch is having conflicts with the latest release, can you please take upstream of the latest changes, fix the conflict and update the PR so we can review it?

2022-09-08 05:45 UTC, kavantrivedi commented
@ocakliemre  just a reminder for resolving conflicts of this branch with the latest release, can you please update this PR so we can review it?

2022-09-08 06:48 UTC, kavantrivedi commented on lib/credit_card_form.dart
> +                          final int lastDayofMonth = DateTime(year, Jiffy( DateTime(year,month)).add(months: 1).month, 0 ).day;
@ocakliemre can we use another way to get the last date of the month, as we do not want any additional package dependencies?

2022-09-08 09:57 UTC, kavantrivedi approved these changes

2022-09-09 08:23 UTC, shwetachauhan-simform requested changes

2022-09-09 08:23 UTC, shwetachauhan-simform commented on lib/credit_card_form.dart
> +                          final DateTime cardDate = DateTime(year, month, lastDayOfMonth,23,59,59,999);
Can you please format this code?

2022-09-09 08:23 UTC, shwetachauhan-simform commented on example/lib/main.dart
> +                            ), backgroundColor: const Color(0xff1b447b),
same here, formatting issue

2022-09-09 08:43 UTC, kavantrivedi commented
Hey @ocakliemre,
Can squash these commits, it would be better to get all changes in a single commit.

2022-09-09 09:29 UTC, shwetachauhan-simform commented
@ocakliemre : You can squash all commit

2022-09-09 10:39 UTC, ShwetaChauhan18 approved these changes

2022-09-09 10:40 UTC, ShwetaChauhan18 approved these changes

2022-09-09 10:41 UTC, shwetachauhan-simform approved these changes

2022-09-12 06:26 UTC, shwetachauhan-simform approved these changes

2022-09-12 06:26 UTC, merged